import { townEventSchema, type TownEvent } from "./schema";

/**
 * Curated festivals and celebrations along the Camino Inglés towns.
 * Dated entries lean on the 2026 season (tour week: mid-September);
 * recurring patron/fiesta dates follow the official Camino Inglés calendar.
 */
const raw: TownEvent[] = [
  {
    id: "event-ferrol-meninas",
    slug: "meninas-de-canido",
    title: "Meninas de Canido",
    kind: "cultural",
    stopIds: ["stop-madalena", "stop-curuxeiras"],
    stageIds: ["stage-1"],
    startDate: "2026-09-05",
    endDate: "2026-09-06",
    whenLabel: "First weekend of September",
    townLabel: "Ferrol",
    summary:
      "Ferrol’s open-air urban art weekend — new Meninas painted in Canido with music, food, and workshops.",
    body: "On the first weekend of September, neighbours and artists restore and add Meninas murals in Canido. Expect street atmosphere, gastronomy, and workshops a short hop from the Madalena grid where Stage 1 begins.",
    practical:
      "Canido is uphill from the harbour start — visit after check-in or on a short arrival day. Confirm the year’s programme locally; 2026 fell on 5–6 September.",
    recurring: true,
    confirmedYear: 2026,
  },
  {
    id: "event-ferrol-san-julian",
    slug: "san-julian-ferrol",
    title: "Día de San Julián",
    kind: "patron",
    stopIds: ["stop-madalena", "stop-curuxeiras"],
    stageIds: ["stage-1"],
    startDate: "2026-01-07",
    endDate: "2026-01-07",
    whenLabel: "7 January",
    townLabel: "Ferrol",
    summary:
      "Ferrol’s patron day — mass at the co-cathedral and the city’s famous rice pudding tasting.",
    body: "Every 7 January Ferrol honours San Julián with liturgical acts and a shared arroz con leche tradition that locals treat as seriously as any procession.",
    practical: "Quiet winter start if you begin the Inglés in January — cafés may keep festive hours.",
    recurring: true,
  },
  {
    id: "event-ferrol-semana-santa",
    slug: "semana-santa-ferrol",
    title: "Semana Santa de Ferrol",
    kind: "celebration",
    stopIds: ["stop-madalena", "stop-curuxeiras"],
    stageIds: ["stage-1"],
    startDate: "2026-03-29",
    endDate: "2026-04-05",
    whenLabel: "Holy Week (movable)",
    townLabel: "Ferrol",
    summary:
      "Processions of International Tourist Interest — naval-city solemnity through Madalena’s streets.",
    body: "Ferrol’s Holy Week tradition reaches back to the 18th-century arsenal city. More than twenty processions, confraternity rites, and exhibitions fill roughly nine days each spring.",
    practical:
      "Expect crowds and street closures near A Madalena. Dates move with Easter — 2026 runs late March into early April.",
    recurring: true,
    confirmedYear: 2026,
  },
  {
    id: "event-neda-festa-do-pan",
    slug: "festa-do-pan-neda",
    title: "Festa do Pan de Neda",
    kind: "gastronomy",
    stopIds: ["stop-neda"],
    stageIds: ["stage-1"],
    startDate: "2026-09-06",
    endDate: "2026-09-06",
    whenLabel: "First Sunday of September",
    townLabel: "Neda",
    summary:
      "Galicia’s celebrated bread festival on Neda’s seaside promenade — Festival of Tourist Interest.",
    body: "Since 1989 Neda has marked the first Sunday of September with artisan loaves, empanada contests, craft stalls, and music along the paseo marítimo. The XXXVI edition in 2026 fell on 6 September with bakeries, vermú, and family workshops.",
    practical:
      "Perfect Stage 1 overnight treat if you arrive Saturday. Stalls typically open mid-morning on the waterfront.",
    recurring: true,
    confirmedYear: 2026,
  },
  {
    id: "event-neda-santa-maria",
    slug: "fiestas-santa-maria-neda",
    title: "Fiestas de Santa María",
    kind: "patron",
    stopIds: ["stop-neda"],
    stageIds: ["stage-1"],
    startDate: "2026-09-08",
    endDate: "2026-09-10",
    whenLabel: "8–10 September",
    townLabel: "Neda",
    summary:
      "Neda’s patron celebrations — liturgy by day, verbena by night, children’s day to close.",
    body: "Santa María brings mass, processions, and evening street parties across three September days. The final day traditionally leans toward games and family attractions.",
    practical: "Noise and late music near the centre — pack earplugs if resting before Stage 2.",
    recurring: true,
  },
  {
    id: "event-neda-feira-camino",
    slug: "feira-do-camino-neda",
    title: "Feira no Camiño de Santiago",
    kind: "cultural",
    stopIds: ["stop-neda"],
    stageIds: ["stage-1"],
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    whenLabel: "June",
    townLabel: "Neda",
    summary:
      "A medieval-flavoured summer fair on the Jacobean streetscape — crafts, costume, and culture.",
    body: "Neda welcomes summer by turning its historic core into a living fair for the Way: markets, period atmosphere, and entertainment woven through the old town pilgrims already walk.",
    practical: "Confirm exact weekend dates each June with the Concello before planning a long lunch stop.",
    recurring: true,
  },
  {
    id: "event-pontedeume-as-peras",
    slug: "fiestas-as-peras",
    title: "Fiestas de As Peras",
    kind: "festival",
    stopIds: ["stop-pontedeume", "stop-castelo-andrade"],
    stageIds: ["stage-2"],
    startDate: "2026-09-07",
    endDate: "2026-09-11",
    whenLabel: "7–11 September",
    townLabel: "Pontedeume",
    summary:
      "Pontedeume’s great patron fiestas for San Nicolás de Tolentino and the Virxe das Virtudes.",
    body: "As Peras fill the Andrade town with mómaros and cabezudos, maritime cucaña, fruit contests, a naval firework battle, and the traditional xira to the Eume. In 2026 the core programme ran 7–11 September.",
    practical:
      "Bridge and riverside streets get busy — arrive early for beds and leave extra time crossing town on Stage 2.",
    recurring: true,
    confirmedYear: 2026,
  },
  {
    id: "event-pontedeume-andrade",
    slug: "feiron-medieval-andrade",
    title: "Feirón Medieval dos Andrade",
    kind: "cultural",
    stopIds: ["stop-pontedeume", "stop-castelo-andrade"],
    stageIds: ["stage-2"],
    startDate: "2026-07-04",
    endDate: "2026-07-05",
    whenLabel: "First weekend of July",
    townLabel: "Pontedeume",
    summary:
      "A medieval fair evoking Pontedeume under the Andrade lords — perfect castle-town atmosphere.",
    body: "On the first weekend of July the historic centre leans into costumes, craft stalls, and period spectacle that retell the family’s coastal power.",
    practical: "Pair with a Castelo dos Andrade visit if legs allow after the Stage 2 climb options.",
    recurring: true,
  },
  {
    id: "event-pontedeume-breamo",
    slug: "romeria-san-miguel-breamo",
    title: "Romería de San Miguel de Breamo",
    kind: "pilgrimage",
    stopIds: ["stop-pontedeume"],
    stageIds: ["stage-2"],
    startDate: "2026-09-29",
    endDate: "2026-09-29",
    whenLabel: "8 May & 29 September",
    townLabel: "Pontedeume",
    summary:
      "Hill hermitage pilgrimage — locals walk up and circle the chapel nine times against the evil eye.",
    body: "Twice a year Pontedeume climbs to San Miguel de Breamo. After mass, tradition says walk nine circuits of the hermitage. The autumn date (29 September) often catches late-season Inglés walkers.",
    practical: "Steep detour from the Camino — only if weather and energy cooperate.",
    recurring: true,
  },
  {
    id: "event-mino-cebola-chata",
    slug: "festa-cebola-chata-mino",
    title: "Festa da Cebola Chata",
    kind: "gastronomy",
    stopIds: ["stop-mino"],
    stageIds: ["stage-2"],
    startDate: "2026-08-01",
    endDate: "2026-08-02",
    whenLabel: "First weekend of August",
    townLabel: "Miño",
    summary:
      "Miño’s flat-onion gastronomic classic — local produce, crafts, music, and Galician stalls.",
    body: "The first August weekend celebrates the cebola chata prized across Galician markets, with craft demos, music, and food stands that turn the coastal town into a tasting ground.",
    practical: "Handy if Stage 2 ends in Miño in early August — book beds early around the weekend.",
    recurring: true,
  },
  {
    id: "event-mino-san-ramon",
    slug: "romeria-san-ramon-mino",
    title: "Romería de San Ramón",
    kind: "pilgrimage",
    stopIds: ["stop-mino"],
    stageIds: ["stage-2"],
    startDate: "2026-08-31",
    endDate: "2026-08-31",
    whenLabel: "31 August",
    townLabel: "Miño",
    summary:
      "Miño’s great country romería in Bra (Sombreu) — over 150 years of tradition and the Posta do Santo.",
    body: "Each 31 August the parish gathers for San Ramón. The climax is the Posta do Santo, a recited prayer handed down within local families, then music and countryside picnic.",
    practical: "Held outside the Camino strip in Bra — ask locals for bus or taxi options if resting in Miño.",
    recurring: true,
  },
  {
    id: "event-mino-san-pedro",
    slug: "fiestas-san-pedro-mino",
    title: "Fiestas de San Pedro",
    kind: "patron",
    stopIds: ["stop-mino"],
    stageIds: ["stage-2"],
    startDate: "2026-06-28",
    endDate: "2026-06-29",
    whenLabel: "Around 28–29 June",
    townLabel: "Miño",
    summary:
      "Patron days for Miño — processions, open-air dances, and a closing fireworks night.",
    body: "San Pedro celebrations run about four days with the biggest energy on 28–29 June: liturgy, parades, verbenas, and fireworks over the estuary town.",
    practical: "Late nights near the centre — plan an easy next morning toward Betanzos.",
    recurring: true,
  },
  {
    id: "event-betanzos-lupulo",
    slug: "festa-do-lupulo-betanzos",
    title: "Festa do Lúpulo",
    kind: "gastronomy",
    stopIds: ["stop-betanzos", "stop-ponte-vella"],
    stageIds: ["stage-3"],
    startDate: "2026-09-11",
    endDate: "2026-09-13",
    whenLabel: "11–13 September 2026",
    townLabel: "Betanzos",
    summary:
      "Hop harvest festival in Praza dos Irmáns García Naveira — Galician beer, food, and live music.",
    body: "Betanzos was once Spain’s hop heartland. The Festa do Lúpulo (second edition in 2026) pairs craft beer culture with field visits, cooking demos, folklore, and concerts in the old-town plazas — timed to the end of harvest.",
    practical:
      "Ideal Stage 3 arrival weekend. Plazas fill Friday–Sunday; confirm albergue space before celebrating.",
    recurring: true,
    confirmedYear: 2026,
  },
  {
    id: "event-betanzos-san-roque",
    slug: "fiestas-san-roque-betanzos",
    title: "Fiestas de San Roque",
    kind: "festival",
    stopIds: ["stop-betanzos", "stop-ponte-vella"],
    stageIds: ["stage-3"],
    startDate: "2026-08-14",
    endDate: "2026-08-18",
    whenLabel: "Around 16 August",
    townLabel: "Betanzos",
    summary:
      "National Tourist Interest — the night balloon, Os Caneiros river party, and full-city festivity.",
    body: "San Roque is Betanzos’s signature summer. Highlights include the giant paper balloon rising over the old town and Os Caneiros, the decorated-boat outing up the Mandeo for an all-day riverside feast.",
    practical: "Hardest beds of the season — reserve before Stage 3 if walking mid-August.",
    recurring: true,
  },
  {
    id: "event-betanzos-tortilla",
    slug: "semana-da-tortilla-betanzos",
    title: "Semana da Tortilla",
    kind: "gastronomy",
    stopIds: ["stop-betanzos"],
    stageIds: ["stage-3"],
    startDate: "2026-08-01",
    endDate: "2026-08-31",
    whenLabel: "August (contest week)",
    townLabel: "Betanzos",
    summary:
      "Restaurants compete for Betanzos’s legendary Spanish omelette crown.",
    body: "Since 2007 the town’s bars and kitchens duel over the runny, onion-forward tortilla that made Betanzos a national reference. Winners often go on to Spain’s broader tortilla contests.",
    practical: "Ask which bars are in the year’s contest — a perfect rest-day lunch before the climb to Bruma.",
    recurring: true,
  },
  {
    id: "event-betanzos-medieval",
    slug: "feira-medieval-betanzos",
    title: "Feira Medieval",
    kind: "cultural",
    stopIds: ["stop-betanzos", "stop-ponte-vella"],
    stageIds: ["stage-3"],
    startDate: "2026-07-12",
    endDate: "2026-07-12",
    whenLabel: "Second Sunday of July",
    townLabel: "Betanzos",
    summary:
      "The Gothic old quarter becomes a medieval stage — crafts, theatre, and music.",
    body: "On the second Sunday of July Betanzos’s historic streets fill with craft stalls, period performance, and music that suit the Cidade dos Cabaleiros nickname.",
    practical: "Enter via Ponte Vella for the classic threshold into the fair.",
    recurring: true,
  },
  {
    id: "event-abegondo-remedios",
    slug: "romeria-remedios-sarandons",
    title: "Romería da Virxe dos Remedios",
    kind: "pilgrimage",
    stopIds: ["stop-bruma", "stop-presedo"],
    stageIds: ["stage-4"],
    startDate: "2026-09-27",
    endDate: "2026-09-27",
    whenLabel: "Fourth Sunday of September",
    townLabel: "Abegondo (near Bruma)",
    summary:
      "Country romería in Sarandóns — masses, Fonte da Santa, and a traditional outdoor meal.",
    body: "On the A Coruña branch near Stage 4 country, Sarandóns honours the Virxe dos Remedios on the fourth Sunday of September (27 September in 2026). Devotees visit the Fonte da Santa, then stay for the campo lunch — pulpo, carne ó caldeiro, and verbena.",
    practical:
      "Slightly off the Ferrol-branch main line — ask in Bruma/Presedo if transport or a short detour is running that Sunday.",
    recurring: true,
    confirmedYear: 2026,
  },
  {
    id: "event-oroso-truita",
    slug: "festa-da-truita-oroso",
    title: "Festa da Truita de Oroso",
    kind: "gastronomy",
    stopIds: ["stop-sigueiro"],
    stageIds: ["stage-5"],
    startDate: "2026-05-09",
    endDate: "2026-05-10",
    whenLabel: "First or second weekend of May",
    townLabel: "Sigüeiro / Oroso",
    summary:
      "Galician Festival of Tourist Interest — trout tastings, fishing contests, crafts, and music.",
    body: "Since 1996 Oroso’s trout festival (centred on Sigüeiro) turns bars and plazas into tasting rooms, with contests for adults and children plus craft and culture around the Tambre approaches.",
    practical: "Confirm the exact May weekend yearly — ideal if Stage 5 lands on festival days.",
    recurring: true,
  },
  {
    id: "event-oroso-cultura",
    slug: "semana-da-cultura-oroso",
    title: "Semana da Cultura de Oroso",
    kind: "cultural",
    stopIds: ["stop-sigueiro"],
    stageIds: ["stage-5"],
    startDate: "2026-08-24",
    endDate: "2026-08-31",
    whenLabel: "Late August",
    townLabel: "Sigüeiro / Oroso",
    summary:
      "Open-air culture week along the Camino corridor — theatre, music, workshops, and water play.",
    body: "Late August brings an open programme across Parque do Carboeiro and the Alameda de Goís, right on the English Way’s inland stretch into Sigüeiro, often paired with Sacramento and verbena nights.",
    practical: "Good last big local party before Compostela — check noise near albergues.",
    recurring: true,
  },
  {
    id: "event-oroso-arte-gois",
    slug: "oroso-gois-arte",
    title: "Oroso–Góis Arte",
    kind: "cultural",
    stopIds: ["stop-sigueiro"],
    stageIds: ["stage-5"],
    startDate: "2026-09-01",
    endDate: "2026-09-30",
    whenLabel: "September",
    townLabel: "Sigüeiro / Oroso",
    summary:
      "Free art exchange with twin town Góis (Portugal), shown at Sigüeiro’s cultural centre.",
    body: "Since 2007 Oroso hosts works by local and Portuguese artists at the Centro Cultural Fernando de Casas y Novoa on Calle de la Cultura in Sigüeiro — a quiet cultural pause before the final stage.",
    practical: "Free entry; hours vary — ask at the cultural centre when you arrive.",
    recurring: true,
  },
  {
    id: "event-santiago-apostol",
    slug: "festas-do-apostolo",
    title: "Festas do Apóstolo",
    kind: "festival",
    stopIds: ["stop-cathedral", "stop-cruceiro-coruna"],
    stageIds: ["stage-6"],
    startDate: "2026-07-18",
    endDate: "2026-07-31",
    whenLabel: "Around 24–25 July (fortnight)",
    townLabel: "Santiago de Compostela",
    summary:
      "Galicia’s great Apostle celebrations — fireworks on the Obradoiro and a city-wide fiesta.",
    body: "For about fifteen days Santiago honours St James. The night of the 24th brings the famous fireworks against a pyrotechnic cathedral façade; the 25th is the solemn feast. Music, dance, folk costume, and another fireworks close near month’s end.",
    practical:
      "Book everything early. Pilgrim Office queues lengthen; arrive at dawn if collecting a Compostela on peak days.",
    recurring: true,
  },
  {
    id: "event-santiago-wos",
    slug: "wos-festival",
    title: "WOS Festival",
    kind: "cultural",
    stopIds: ["stop-cathedral"],
    stageIds: ["stage-6"],
    startDate: "2026-09-11",
    endDate: "2026-09-13",
    whenLabel: "11–13 September 2026",
    townLabel: "Santiago de Compostela",
    summary:
      "Indoor avant-garde festival in heritage venues — electronic music, visuals, film, and talks.",
    body: "WOS (Work On Sunday) fills unique Compostela spaces each September with exploratory music and multidisciplinary art. The 2026 edition ran 11–13 September across high-heritage rooms in the historic city.",
    practical: "Ticketed indoor events — check venues if finishing the Camino that weekend.",
    recurring: true,
    confirmedYear: 2026,
  },
  {
    id: "event-santiago-street",
    slug: "compostela-street",
    title: "Compostela Street",
    kind: "festival",
    stopIds: ["stop-cathedral"],
    stageIds: ["stage-6"],
    startDate: "2026-09-18",
    endDate: "2026-09-20",
    whenLabel: "18–20 September 2026",
    townLabel: "Santiago de Compostela",
    summary:
      "Free urban culture and extreme-sports festival on the south university campus.",
    body: "Compostela Street gathers competitions, shows, concerts, workshops, a street market, and food stalls across up to ten urban disciplines — open to all audiences.",
    practical: "Campus Universitario Sur is a bus or walk from the cathedral — easy rest-day outing after arrival.",
    recurring: true,
    confirmedYear: 2026,
  },
  {
    id: "event-santiago-mare",
    slug: "mare-festival",
    title: "Maré — Festival de Músicas e Artes Atlánticas",
    kind: "cultural",
    stopIds: ["stop-cathedral"],
    stageIds: ["stage-6"],
    startDate: "2026-09-23",
    endDate: "2026-09-27",
    whenLabel: "23–27 September 2026",
    townLabel: "Santiago de Compostela",
    summary:
      "Atlantic music and arts across historic-city venues — sounds from both shores of the ocean.",
    body: "Maré turns Compostela into a meeting point for Atlantic cultures: concerts and arts events in venues threaded through the old city, ideal for pilgrims lingering after the Obradoiro.",
    practical: "Programme spans several days — pick one evening show rather than rushing after a walking day.",
    recurring: true,
    confirmedYear: 2026,
  },
  {
    id: "event-santiago-ascension",
    slug: "festas-da-ascensión",
    title: "Festas da Ascensión",
    kind: "celebration",
    stopIds: ["stop-cathedral"],
    stageIds: ["stage-6"],
    startDate: "2026-05-14",
    endDate: "2026-05-21",
    whenLabel: "Sixth Thursday after Easter (week)",
    townLabel: "Santiago de Compostela",
    summary:
      "The city’s second great fiesta after the Apostle — popular, cultural, and student-spirited.",
    body: "Ascension week mixes official programme with university energy before exam season. Expect concerts, fairs, and crowded plazas for about seven days on a movable spring date.",
    practical: "Dates shift yearly with Easter — verify before planning a Compostela layover.",
    recurring: true,
    confirmedYear: 2026,
  },
];

export const townEvents: TownEvent[] = raw.map((e) => townEventSchema.parse(e));

export function getTownEventBySlug(slug: string) {
  return townEvents.find((e) => e.slug === slug);
}

export function getTownEventById(id: string) {
  return townEvents.find((e) => e.id === id);
}

export function getEventsForStop(stopId: string) {
  return townEvents.filter((e) => e.stopIds.includes(stopId));
}

export function getEventsForStage(stageId: string) {
  return townEvents.filter((e) => e.stageIds.includes(stageId));
}
